import type { Metadata } from "next";

import Header from "@components/Header/Header";
import Footer from "@components/Footer/Footer";
import "./globals.css";
import {Exo_2, Inter, Noto_Sans,Roboto,Poppins } from 'next/font/google'

export  const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})
export const titleFont = Exo_2({
  weight: ["500", "600", "700"],
  subsets: ["latin"],
});

export const textFont = Noto_Sans({
  weight: ["500", "600", "700"],
  subsets: ["latin"],
});

export  const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={`${inter.className} ${roboto.className} bg-primary-100`}>
        {/* <Header /> */}
          {children}
       {/* <Footer/> */}
      </body>
    </html>
  );
}
